version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NAME=World
    command: pdm run uvicorn src.main:app --host 0.0.0.0 --port 8000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
      image: mongo-express #admin:pass
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/