version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672 #rabbit
      - 15672:15672 #management vychozi heslo guest:guest

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=wab_4
  mongo-express: #admin:pass
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081
