[project]
name = ""
version = ""
description = ""
authors = [
    {name = "xmalak", email = "xmalak@mendelu.cz"},
]
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn>=0.23.2",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

